// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCqsCUQfK7bYeAMN1JJnqTmycebh2-ZS8',
    appId: '1:152712731069:web:72e9e0e50d4cf5b8941ad4',
    messagingSenderId: '152712731069',
    projectId: 'inbook-3f1b8',
    authDomain: 'inbook-3f1b8.firebaseapp.com',
    storageBucket: 'inbook-3f1b8.firebasestorage.app',
    measurementId: 'G-M7L3N9FW7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGyNXk7LUgE55Q05xGvW7HtnL2GFQnVrk',
    appId: '1:152712731069:android:8b0deb4f3d171b4d941ad4',
    messagingSenderId: '152712731069',
    projectId: 'inbook-3f1b8',
    storageBucket: 'inbook-3f1b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4p3xgUmC7GBY3iagaorot-dJVjeriWKc',
    appId: '1:152712731069:ios:c71fe16f45f71840941ad4',
    messagingSenderId: '152712731069',
    projectId: 'inbook-3f1b8',
    storageBucket: 'inbook-3f1b8.firebasestorage.app',
    iosBundleId: 'com.example.inBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4p3xgUmC7GBY3iagaorot-dJVjeriWKc',
    appId: '1:152712731069:ios:c71fe16f45f71840941ad4',
    messagingSenderId: '152712731069',
    projectId: 'inbook-3f1b8',
    storageBucket: 'inbook-3f1b8.firebasestorage.app',
    iosBundleId: 'com.example.inBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCqsCUQfK7bYeAMN1JJnqTmycebh2-ZS8',
    appId: '1:152712731069:web:38e1e253de6591eb941ad4',
    messagingSenderId: '152712731069',
    projectId: 'inbook-3f1b8',
    authDomain: 'inbook-3f1b8.firebaseapp.com',
    storageBucket: 'inbook-3f1b8.firebasestorage.app',
    measurementId: 'G-VV2MWMXPTL',
  );
}
